### ISSUE TITLE
installed roop, it shows up in SD but doen'st work.

### ISSUE THREAD

**Issue by Zingercustoms** [s0md3v/sd-webui-roop#105]
at first I was getting errors in the cmd saying faceswap.py was missing, i fixed the lines 21,22 and that error went away. now if I open up the install log for roop in the extension folder it says this at the end:

 except Exception as e:
            print(e)
            print(f"Warning: Failed to install {package}, roop will not work.")
            raise e

I already downloaded the inswapper_128.onnx file and replaced it in the model folder.

can't figure it out.  I get no errors in SD cmd load screen.

please help, thanks

**Comment by rauldlnx10** [comment]
But you see the extension in your SD? I mean, you can use it but if you are trying to do nsfw content ifnude will make it not work.
