### ISSUE TITLE
 ERROR: Could not install packages due to an OSError: [WinError 5] 

### ISSUE THREAD

**Issue by ELN23** [s0md3v/sd-webui-roop#106]
Hi, I'm getting this error when I try to install it. Thankfull for any help, I'm no expert at this.... 

 ERROR: Could not install packages due to an OSError: [WinError 5] ... Check the permissions"

**Comment by adifelice-godaddy** [comment]
You have to activate the virtual environment. step on your `stable-diffusion-webui` directory:
```
C:\Users\user\stable-diffusion-webui>venv\Scripts\activate.bat
```
You should see the `(venv)` shell prefix. Then you can install:
```
(venv) C:\Users\user\stable-diffusion-webui>pip install insightface==0.7.3
```

**Comment by ELN23** [comment]
I'll didn't understand your instructions (layman...) but told ChatGPT to explain it to me. And it worked :)! Thanks man, that was it. I tried a million things unsuccesfully before.

**Comment by BabyLittelFinger** [comment]
> pip install insightface==0.7.3

I did as you had said, but I still have the same problem and also these two warnings:  Ignoring invalid distribution -pencv-python, Ignoring invalid distribution -rotobuf.
