### ISSUE TITLE
How to change 【buffalo_l】 default download location for C:

### ISSUE THREAD

**Issue by LIU-ZHIHAO** [s0md3v/sd-webui-roop#108]
<img width="1118" alt="image" src="https://github.com/s0md3v/sd-webui-roop/assets/24649106/885cc5de-fdc6-4b20-8002-78da0a07c15a">
I found that when I run roop for the first time, many model files will be stored under C:\User\name\.insightface\model\buffalo_l\, which will cause a hidden danger of insufficient space on my C drive. Can you Custom settings to change the storage path of the model，thinks！

**Comment by Aptronymist** [comment]
Not only that, but the zip file that contained the models was still there, so it was consuming even more space.
