### ISSUE TITLE
No "roop" drop-down menu

### ISSUE THREAD

**Issue by boobilon5** [s0md3v/sd-webui-roop#109]
HI!

I have installed the extantion, but it does not show up in the interface. **I've read all issue reports here, nothing worked for me.**

Also this:

![image](https://github.com/s0md3v/sd-webui-roop/assets/137882824/ea818d99-83a3-49a3-81f2-39f2b02fffd5)

Insightface is installed and updated, VS (Python, C++ etc) is instulled.

**Comment by boobilon5** [comment]
After reinstaling insightface and onnxruntime got new pack of errors:

![image](https://github.com/s0md3v/sd-webui-roop/assets/137882824/cb2ee2a2-45f1-44a2-ad2e-623bd9709904)

**Comment by boobilon5** [comment]
wtf

**Comment by bevebkba** [comment]
i have the same problem

**Comment by jyotirmoypaul** [comment]
Here is what I did,
Install **Visual Studio Build Tools** with **Python, C++, Windows 10 and 11 SDK** enabled.
Uninstall _insightface_ globally with this command `pip uninstall insightface` 
Then activate **venv**, from stable diffusion main folder _\venv\Scripts_ Open **cmd** there and activate **venv** with the command `activate`
Run this command `pip uninstall insightface` to ensure if _insightface_ is also deleted from **venv**. Close **cmd**.
Then manually delete every folder you find named _insightface_. From the global library, from any virtual environment, from stable diffusion **venv** folder, from everywhere you can.
Delete **sd-webui-roop** folder from extensions.
Now Open **webui-user.bat** file again to run stable diffusion.
Install **sd-webui-roop** again from **Extensions** tab. **Apply and restart UI**. Then close stable diffusion.
Then again activate **venv** from stable diffusion main folder _\venv\Scripts_ Open **cmd** there and activate **venv** with the command `activate`
Now run this command `pip install -r \extensions\sd-webui-roop\requirements.txt` here you have to put the path of your **roop extension's requirements.txt**
It will recheck for _insightface_ and install it again inside **venv**.
Now Open **webui-user.bat** file again to run stable diffusion, now hopefully, You can see **Roop** menu.

**Comment by marcojoao** [comment]
I'm getting this error when trying to instal insightface on linux: `pip install -r extensions/sd-webui-roop/requirements.txt 
Collecting insightface==0.7.3 (from -r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting onnx==1.14.0 (from -r extensions/sd-webui-roop/requirements.txt (line 2))
  Using cached onnx-1.14.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
Collecting onnxruntime==1.15.0 (from -r extensions/sd-webui-roop/requirements.txt (line 3))
  Downloading onnxruntime-1.15.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 9.7 MB/s eta 0:00:00
Collecting opencv-python==4.7.0.72 (from -r extensions/sd-webui-roop/requirements.txt (line 4))
  Using cached opencv_python-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.8 MB)
Collecting ifnude (from -r extensions/sd-webui-roop/requirements.txt (line 5))
  Downloading ifnude-0.0.3-py2.py3-none-any.whl (7.1 kB)
Requirement already satisfied: cython in ./venv/lib/python3.9/site-packages (from -r extensions/sd-webui-roop/requirements.txt (line 6)) (0.29.35)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1)) (1.25.0)
Collecting tqdm (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting requests (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting matplotlib (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached matplotlib-3.7.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting Pillow (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached Pillow-9.5.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.4 MB)
Collecting scipy (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.5 MB)
Collecting scikit-learn (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached scikit_learn-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
Collecting scikit-image (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached scikit_image-0.21.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.8 MB)
Collecting easydict (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached easydict-1.10-py3-none-any.whl
Collecting albumentations (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Collecting prettytable (from insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached prettytable-3.8.0-py3-none-any.whl (27 kB)
Collecting protobuf>=3.20.2 (from onnx==1.14.0->-r extensions/sd-webui-roop/requirements.txt (line 2))
  Using cached protobuf-4.23.3-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
Collecting typing-extensions>=3.6.2.1 (from onnx==1.14.0->-r extensions/sd-webui-roop/requirements.txt (line 2))
  Using cached typing_extensions-4.7.0-py3-none-any.whl (33 kB)
Collecting coloredlogs (from onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers (from onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting packaging (from onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting sympy (from onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting opencv-python-headless>=4.5.1.48 (from ifnude->-r extensions/sd-webui-roop/requirements.txt (line 5))
  Using cached opencv_python_headless-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.2 MB)
Collecting PyYAML (from albumentations->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
Collecting qudida>=0.0.4 (from albumentations->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting networkx>=2.8 (from scikit-image->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting imageio>=2.27 (from scikit-image->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached imageio-2.31.1-py3-none-any.whl (313 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached tifffile-2023.4.12-py3-none-any.whl (219 kB)
Collecting PyWavelets>=1.1.1 (from scikit-image->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached PyWavelets-1.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Collecting lazy_loader>=0.2 (from scikit-image->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached lazy_loader-0.2-py3-none-any.whl (8.6 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting contourpy>=1.0.1 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached contourpy-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
Collecting cycler>=0.10 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached fonttools-4.40.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Collecting kiwisolver>=1.0.1 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached kiwisolver-1.4.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting pyparsing>=2.3.1 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached pyparsing-3.1.0-py3-none-any.whl (102 kB)
Collecting python-dateutil>=2.7 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting wcwidth (from prettytable->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting charset-normalizer<4,>=2 (from requests->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Collecting idna<4,>=2.5 (from requests->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting joblib>=1.1.1 (from scikit-learn->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached joblib-1.3.1-py3-none-any.whl (301 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting mpmath>=0.19 (from sympy->onnxruntime==1.15.0->-r extensions/sd-webui-roop/requirements.txt (line 3))
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting zipp>=3.1.0 (from importlib-resources>=3.2.0->matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->insightface==0.7.3->-r extensions/sd-webui-roop/requirements.txt (line 1))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for insightface (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [249 lines of output]
      WARNING: pandoc not enabled
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/insightface
      copying insightface/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface
      creating build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/transform.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/storage.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/filesystem.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/face_align.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/download.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/constant.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      copying insightface/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/utils
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty
      copying insightface/thirdparty/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty
      creating build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/scrfd.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/retinaface.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/model_zoo.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/model_store.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/landmark.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/inswapper.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/attribute.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/arcface_onnx.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      copying insightface/model_zoo/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/model_zoo
      creating build/lib.linux-x86_64-cpython-39/insightface/data
      copying insightface/data/rec_builder.py -> build/lib.linux-x86_64-cpython-39/insightface/data
      copying insightface/data/pickle_object.py -> build/lib.linux-x86_64-cpython-39/insightface/data
      copying insightface/data/image.py -> build/lib.linux-x86_64-cpython-39/insightface/data
      copying insightface/data/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/data
      creating build/lib.linux-x86_64-cpython-39/insightface/commands
      copying insightface/commands/rec_add_mask_param.py -> build/lib.linux-x86_64-cpython-39/insightface/commands
      copying insightface/commands/model_download.py -> build/lib.linux-x86_64-cpython-39/insightface/commands
      copying insightface/commands/insightface_cli.py -> build/lib.linux-x86_64-cpython-39/insightface/commands
      copying insightface/commands/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/commands
      creating build/lib.linux-x86_64-cpython-39/insightface/app
      copying insightface/app/mask_renderer.py -> build/lib.linux-x86_64-cpython-39/insightface/app
      copying insightface/app/face_analysis.py -> build/lib.linux-x86_64-cpython-39/insightface/app
      copying insightface/app/common.py -> build/lib.linux-x86_64-cpython-39/insightface/app
      copying insightface/app/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/app
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d
      copying insightface/thirdparty/face3d/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/morphable_model
      copying insightface/thirdparty/face3d/morphable_model/morphabel_model.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/morphable_model
      copying insightface/thirdparty/face3d/morphable_model/load.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/morphable_model
      copying insightface/thirdparty/face3d/morphable_model/fit.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/morphable_model
      copying insightface/thirdparty/face3d/morphable_model/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/morphable_model
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/vis.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/transform.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/render.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/light.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/io.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      copying insightface/thirdparty/face3d/mesh_numpy/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh_numpy
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/vis.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/transform.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/render.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/light.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/io.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      copying insightface/thirdparty/face3d/mesh/__init__.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      running egg_info
      writing insightface.egg-info/PKG-INFO
      writing dependency_links to insightface.egg-info/dependency_links.txt
      writing entry points to insightface.egg-info/entry_points.txt
      writing requirements to insightface.egg-info/requires.txt
      writing top-level names to insightface.egg-info/top_level.txt
      reading manifest file 'insightface.egg-info/SOURCES.txt'
      writing manifest file 'insightface.egg-info/SOURCES.txt'
      /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.images' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.images' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'insightface.data.images' to be distributed and are
              already explicitly excluding 'insightface.data.images' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.data.objects' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.data.objects' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'insightface.data.objects' to be distributed and are
              already explicitly excluding 'insightface.data.objects' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
              already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/Tom_Hanks_54745.png -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/mask_black.jpg -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/mask_blue.jpg -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/mask_green.jpg -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/mask_white.jpg -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      copying insightface/data/images/t1.jpg -> build/lib.linux-x86_64-cpython-39/insightface/data/images
      creating build/lib.linux-x86_64-cpython-39/insightface/data/objects
      copying insightface/data/objects/meanshape_68.pkl -> build/lib.linux-x86_64-cpython-39/insightface/data/objects
      creating build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/mesh_core.h -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.c -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      copying insightface/thirdparty/face3d/mesh/cython/setup.py -> build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/insightface
      creating build/temp.linux-x86_64-cpython-39/insightface/thirdparty
      creating build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d
      creating build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh
      creating build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython
      gcc -pthread -B /home/marcojoao/mambaforge/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/marcojoao/mambaforge/include -fPIC -O2 -isystem /home/marcojoao/mambaforge/include -fPIC -Iinsightface/thirdparty/face3d/mesh/cython -I/tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include -I/resources/repos/stable-diffusion-webui/venv/include -I/home/marcojoao/mambaforge/include/python3.9 -c insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp -o build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython/mesh_core.o
      gcc -pthread -B /home/marcojoao/mambaforge/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/marcojoao/mambaforge/include -fPIC -O2 -isystem /home/marcojoao/mambaforge/include -fPIC -Iinsightface/thirdparty/face3d/mesh/cython -I/tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include -I/resources/repos/stable-diffusion-webui/venv/include -I/home/marcojoao/mambaforge/include/python3.9 -c insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp -o build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.o
      In file included from /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp:784:
      /tmp/pip-build-env-yxr0voj7/overlay/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      g++ -pthread -B /home/marcojoao/mambaforge/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/marcojoao/mambaforge/lib -Wl,-rpath-link,/home/marcojoao/mambaforge/lib -L/home/marcojoao/mambaforge/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/marcojoao/mambaforge/lib -Wl,-rpath-link,/home/marcojoao/mambaforge/lib -L/home/marcojoao/mambaforge/lib build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython/mesh_core.o build/temp.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.o -o build/lib.linux-x86_64-cpython-39/insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpython-39-x86_64-linux-gnu.so
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /home/marcojoao/mambaforge/compiler_compat/ld: cannot find /usr/lib/libm.so.6
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /home/marcojoao/mambaforge/compiler_compat/ld: cannot find /usr/lib/libmvec.so.1
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /home/marcojoao/mambaforge/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /home/marcojoao/mambaforge/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects`

**Comment by henrikmk** [comment]
Followed [jyotirmoypaul](https://github.com/jyotirmoypaul)'s instructions, but they still give [marcojoao](https://github.com/marcojoao)'s result.
