### ISSUE TITLE
AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by kalminervin** [s0md3v/sd-webui-roop#110]
Hi, getting this error below at the postprocess stage. "Enable" is tickes, and the "Restore face" also. I get an image, but without face being swaped. Thanks!

Error running postprocess_image: C:\Users\Admin\Documents\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\Admin\Documents\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\Admin\Documents\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by JScottMacD** [comment]
I get the same error, worked fine last night, 

These all updated when I started up this morning, so not sure if one of these would cause the issue.

LDSR                                built-in None Tue Jun 27 10:59:31 2023
Lora                                 built-in None Tue Jun 27 10:59:31 2023
ScuNET                            built-in None Tue Jun 27 10:59:31 2023
SwinIR                              built-in None Tue Jun 27 10:59:31 2023
canvas-zoom-and-pan    built-in None Tue Jun 27 10:59:31 2023
extra-options-section      built-in None Tue Jun 27 10:59:31 2023
prompt-bracket-checker built-in None Tue Jun 27 10:59:31 2023

**Comment by SandUhrGucker** [comment]
Info for others: I got the same Error message. The reason was sd-webui-roop and vid-faceswap were enabled simultaneous.
