### ISSUE TITLE
Quality mismatch problem

### ISSUE THREAD

**Issue by tomika** [s0md3v/sd-webui-roop#113]
The resolution of the replaced face is way below the original image and upscale parameter do not help at all.
On some images there is a clearly visible line at the border of the replacement.
![roop1](https://github.com/s0md3v/sd-webui-roop/assets/116955/8d3906fc-3673-4486-b97e-52ae188b7408)
As you can see on this picture, the quality heavily degraded inside the replaced rectangle. (Look at the edge of the face or the edge of the shirt or the hair becames blurry and distorted within the replaced rectangle)
Or
![roop2](https://github.com/s0md3v/sd-webui-roop/assets/116955/bde598e0-9e45-42aa-a2af-35e0adb1869c)
It has been created with around 700x800 input face with 8x upscaler scale

**Comment by jyuan15** [comment]
Much better with Hires.fix

**Comment by WeirdScienceX** [comment]
I agree, the roop generated area is really low quality in comparison to the rest of the image, upscaling within the extension doesn't help at all.

**Comment by s0md3v** [comment]
This is an issue with the third-party model being used, nothing I can do here.
