### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nottengame** [s0md3v/sd-webui-roop#12]
**Hello! 
Thank you for this plugin, looks very promissing!** 

But while trying to swap face in txt2img tab getting an error:

`13:15:27-568317 ERROR    Running script postprocess image:
                         C:\Stable-Diffusion\vlad1111\automatic\extensions\sd-webui-roop\scripts\faceswap.py:
                         AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Stable-Diffusion\vlad1111\automatic\modules\scripts.py:466 in postprocess_image                                   │
│                                                                                                                      │
│   465 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 466 │   │   │   │   script.postprocess_image(p, pp, *args)                                                         │
│   467 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                      │
│                                                                                                                      │
│ C:\Stable-Diffusion\vlad1111\automatic\extensions\sd-webui-roop\scripts\faceswap.py:187 in postprocess_image         │
│                                                                                                                      │
│   186 │   │   │   │   image: Image.Image = script_pp.image                                                           │
│ ❱ 187 │   │   │   │   result: ImageResult = swap_face(                                                               │
│   188 │   │   │   │   │   self.source,                                                                               │
│                                                                                                                      │
│ C:\Stable-Diffusion\vlad1111\automatic\extensions\sd-webui-roop\scripts\swapper.py:125 in swap_face                  │
│                                                                                                                      │
│   124 │   │   │   │   if target_face is not None:                                                                    │
│ ❱ 125 │   │   │   │   │   result = face_swapper.get(result, target_face, source_face)                                │
│   126 │   │   │   │   else:                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'get'`

Plus, label for the last field in an extension tab is 
"_Model not found, please download one and reload automatic 1111_" 
And it is not clear which model I have to download.

**Comment by nottengame** [comment]
@MikeKashko Thanks for advice, but I believe the same model is located in \extensions\sd-webui-roop\models\roop\
name and size are exactly the same. 
and in the 'model' folder, there is no folder named FaceSwap. 
After I created this folder, I started getting warning messege from roop when loading automatic: 
`2023-06-19 14:30:31,392 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/`

**Comment by MikeKashko** [comment]
At first I also placed the model in '\extensions\sd-webui-roop\models\FaceSwap' and I had the same problem as you.
Is there a folder called 'roop' in 'stable-diffusion-webui\models\'?
If so, copy the model into it.

**Comment by suphamster** [comment]
To fix "result = face_swapper.get(result, target_face, source_face)" error just install original version and **do not use** this one https://github.com/Em1tSan/sd-webui-roop-unlock (or replace scripts in "..\sd-webui-roop-unlock\scripts" with original, delete "__pycache__" folder there, close console with opened tool, install "ifnude" and "xformers" modules here "..\venv\Lib\site-packages"" and start webui or webui-user bat file again.)

**Comment by nottengame** [comment]
@s0md3v Hello!
I previously used https://github.com/kex0/batch-face-swap 
But the quality of outputs was often very poor, so I deleted it.

**Comment by visaeon** [comment]
Im getting the same issue here .
The file is in the roop models folder and i also created a faceswap folder to test it but i have the same problem as the OP

**Comment by visaeon** [comment]
Error running postprocess_batch: A:\machine learning\Text To Image\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "A:\machine learning\Text To Image\stable-diffusion-webui\modules\scripts.py", line 454, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "A:\machine learning\Text To Image\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 187, in postprocess_image
    result: ImageResult = swap_face(
  File "A:\machine learning\Text To Image\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 134, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by s0md3v** [comment]
If you encounter this error, download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside `<webui_dir>/models/roop/` directory.
