### ISSUE TITLE
Failed to install ifnude，pip install ifnude also not work！

### ISSUE THREAD

**Issue by vaporlee** [s0md3v/sd-webui-roop#120]
*** Error running install.py for extension C:\Users\menge\Documents\sd webui\webui\extensions\sd-webui-roop.
*** Command: "C:\Users\menge\Documents\sd webui\system\python\python.exe" "C:\Users\menge\Documents\sd webui\webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stdout: Checking roop requirements
*** Install insightface==0.7.3
*** Installing sd-webui-roop requirement: insightface==0.7.3
*** Install onnx==1.14.0
*** Installing sd-webui-roop requirement: onnx==1.14.0
*** Install onnxruntime==1.15.0
*** Installing sd-webui-roop requirement: onnxruntime==1.15.0
*** Install opencv-python==4.7.0.72
*** Installing sd-webui-roop requirement: opencv-python==4.7.0.72
*** Install ifnude
*** Installing sd-webui-roop requirement: ifnude
*** Couldn't install sd-webui-roop requirement: ifnude.
*** Command: "C:\Users\menge\Documents\sd webui\system\python\python.exe" -m pip install ifnude --prefer-binary
*** Error code: 1
*** stdout: Looking in indexes: http://pypi.mirrors.ustc.edu.cn/simple/
***
*** stderr: ERROR: Could not find a version that satisfies the requirement ifnude (from versions: none)
*** ERROR: No matching distribution found for ifnude
***
*** Warning: Failed to install ifnude, roop will not work.

**Comment by vaporlee** [comment]
C:\Users\menge>pip install ifnude
Looking in indexes: http://pypi.mirrors.ustc.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement ifnude (from versions: none)
ERROR: No matching distribution found for ifnude

**Comment by jyuan15** [comment]
Please use the official source of pip.

**Comment by AnnieBunnieX** [comment]
What is the python version?

**Comment by vaporlee** [comment]
> What is the python version?

Python 3.10.10

**Comment by vaporlee** [comment]
> Please use the official source of pip.

How I change it?

**Comment by Loly-Pop** [comment]
I can you please be more concrete.... you helping no-one........ what do you said by         I found the url in "%APPDATA%\pip\pip.ini" then I changed it.It's working now! ?????????????? We come here to figuring out how to fix this !!!!!!!!!!!! So........ we are waiting for an real ansewr.......... !!!!!!!!!!!!!!!!!
