### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Maddoxyoung** [s0md3v/sd-webui-roop#122]
when generating a image with roop enabled i get this error: 

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}| 30/30 [01:17<00:00,  2.65s/it]
find model: C:\Users\Ali/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
R:\Software\SD_AMD\webui\stable-diffusion-webui-directml\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Ali/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Error running postprocess_batch: R:\Software\SD_AMD\webui\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "R:\Software\SD_AMD\webui\stable-diffusion-webui-directml\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "R:\Software\SD_AMD\webui\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "R:\Software\SD_AMD\webui\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

I downloaded inswapper_128.onnx and put it inside <webui_dir/models/roop> but the error remains.
the image does get generated but roop has no effect

**Comment by gan** [comment]
same issue

**Comment by Limbicnation** [comment]
> same issue
> 
> I found that the size of the "inswapper_128.onnx" file in the "roop" folder is different from the size of the file downloaded through [the link](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx), so I replaced it. Then, restart the webUI, and everything is fine.

Unfortunately, this method didn't work for me.

**Comment by Limbicnation** [comment]
> > same issue
> > I found that the size of the "inswapper_128.onnx" file in the "roop" folder is different from the size of the file downloaded through [the link](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx), so I replaced it. Then, restart the webUI, and everything is fine.
> 
> Unfortunately, this method didn't work for me.

I made a mistake by copying the model into the wrong folder. Instead of ./extensions/sd-webui-roop/models, it should have been copied to ./models/roop/.
