### ISSUE TITLE
only image works? dont support video?

### ISSUE THREAD

**Issue by PuddingJoker** [s0md3v/sd-webui-roop#13]
only image works? dont support video?

**Comment by Gourieff** [comment]
Yes, only images
But you can do a batch process (of extracted frames, for example) and then merge resulted pictures with ffmpeg

**Comment by s0md3v** [comment]
For videos, use https://github.coms/s0md3v/roop

**Comment by PuddingJoker** [comment]
> Yes, only images But you can do a batch process (of extracted frames, for example) and then merge resulted pictures with ffmpeg

thanks!

**Comment by PuddingJoker** [comment]
> For videos, use https://github.coms/s0md3v/roop

okay
