### ISSUE TITLE
Could not build wheels for insightface which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by LouisLU1997** [s0md3v/sd-webui-roop#134]
hi bro how to deal this promblem？

ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface which use PEP 517 and cannot be installed directly

![image](https://github.com/s0md3v/sd-webui-roop/assets/129682640/0f21d1b2-2210-4e34-a690-92245cf13963)

**Comment by Lee3S** [comment]
Have you solved it yet?
