### ISSUE TITLE
roop face are :neutral_face:   

### ISSUE THREAD

**Issue by mostafablender** [s0md3v/sd-webui-roop#139]
Hi  , first  thank you for all you do ,  second , when i create image in stable diffusion with roop   not matter if the target image or input  image or even both have emotions to them like Anger  or sadness or oven mouth open  , anything  it wont show in the generated image ,  what should i do ? is this a problem that going to be fix  later or i do something wrong ?

**Comment by GlukXP** [comment]
I used a photo of Angelina Jolie from the red carpet and Brezhnev (funny expression). Checked "Swap in source image" and "Denoising strength: 0.05".

Works!

**Comment by bjbjbjbj** [comment]
> 



> I used a photo of Angelina Jolie from the red carpet in the extension and Brezhnev (a funny expression as a basis). "Swap in original image" and "Noise reduction strength: 0.05" are checked.
> 
> Works! Although not too accurate, it replaces eyebrows and other small details.
> 
> ControlNet Canny can help.

how to set Noise reduction strength: 0.05?
