### ISSUE TITLE
Roop is using CPU instead of GPU

### ISSUE THREAD

**Issue by waelmansourx** [s0md3v/sd-webui-roop#140]
I'm getting this message and it's using CPU instead of GPU

`Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}`

**Comment by GlukXP** [comment]
> I'm getting this message and it's using CPU instead of GPU
> 
> `Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}`

Because it uses the CPU by default.
I watched the original ROOP and there you can switch to GPU acceleration, although not without problems.
It seems that such a function is simply not made here.

**Comment by kukalikuk** [comment]
> Update!
> 
> I tried to force turn on the GPU using the solution from here: https://github.com/s0md3v/roop/wiki/2.-Acceleration
> 
> However, setting onnxruntime-gpu==1.15.0 causes onnxruntime error 126
> 
> win10 system GPU 3060 12Gb
> 
> Everything is installed and reinstalled according to the instructions.
> 
> Long story short: I'm waiting for updates.

does it faster using GPU? I tried solution from that link and it gave me more messages in the console. I'm also using 3060 12GB and CPUproviders give +7secs/face swap but CUDAproviders make it longer to +20secs/face swap because the long messages

We discussed here https://github.com/s0md3v/sd-webui-roop/issues/74 but dunno why @s0md3v mark it as closed

**Comment by Gourieff** [comment]
Using GPU makes sense if you're swapping video and really have a giant batch of frames
But in the case of swapping photo (even some batch) CPU works rather fast, even faster than with GPU, because CPU Execution Provider loads very quick

**Comment by s0md3v** [comment]
Intended.

**Comment by DniproOFF** [comment]
I have the same problem, only my game **loads the GPU**, not the processor
