### ISSUE TITLE
Feature request - Multiple roop tabs like control net

### ISSUE THREAD

**Issue by JamesMcMurran** [s0md3v/sd-webui-roop#147]
It would be super helpful to have multiple tabs of Roop like we have in the control net. This way we can swap multiple characters in an image in one go. 
We could also use it where the first tab has a base face then the second tab has a different angle of the face. We could even give it two different faces for the same subject making a face bash.

**Comment by afeezaziz** [comment]
You can copy the same folder but rename it as 2, 3, and so on and you can have multiple roop tabs.

**Comment by s0md3v** [comment]
You can already replace multiple characters in one go. You can use "send to img2img" infinite times.

**Comment by xiyu-lds** [comment]
How can I use Multiple roop in the api
