### ISSUE TITLE
Roop only works half of the time and not all the time

### ISSUE THREAD

**Issue by zaselim** [s0md3v/sd-webui-roop#154]
Hi,
So as the title says, half of the time roop doesn't start where it suppose to after the image render finishes. And in img2img, it doesn't around 80% of the time. I code just doesn't start in the cmd window. And 20% of the time it works after trying many time (like i said 80% of the time doesn't work) when shifting sampling method (between DDIM and DPM++ SDE Karsas as these are the ones i use mostly).
I don't care about img to img, the only reason i use roop in img2img when roop doesn't start in txt2img as I mentioned above.
Is there any fix for that?
Thanks.

**Comment by SwatMessiah** [comment]
its because it detects nudity - then it will not swap the face

**Comment by ramnnv** [comment]
> its because it detects nudity - then it will not swap the face - you could disable it like this (at your own responsibility) it returns True if there is a nude shape - you could also just write "return False"
> 
> cimage.py: ![grafik](https://user-images.githubusercontent.com/124623065/252139932-a85e8d3c-0a6f-4693-987c-59b7e5d4a23a.png)

i dont understand, can you explain it better? where, in what line i need to put the "return False"

**Comment by s0md3v** [comment]
Read the disclaimer.
