### ISSUE TITLE
faceswap.py error

### ISSUE THREAD

**Issue by KNUPAC** [s0md3v/sd-webui-roop#156]
Hi, 

I'm getting constant error when using img2img, some user here pointed out on #33 - swapping line 21/22 
but wasn't working, this issue keep persisting. 

Need help! 

*** Error running postprocess_image: E:\AI\webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\AI\webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\AI\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by ylmalta** [comment]
same problem

**Comment by Gourieff** [comment]
You need to disable "SD-CN-Animation" extension

**Comment by KNUPAC** [comment]
> You need to disable "SD-CN-Animation" extension

I don't have that extension installed. 

Plus, i have re-install roop multiple time (delete folder included)

**Comment by Gourieff** [comment]
It conflicts with one of extensions I suppose, try to disable some of them
