### ISSUE TITLE
Help needed, img2img doesnt work, AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by ylmalta** [s0md3v/sd-webui-roop#157]
I spent one whole day to fix it but still not work, img2 img，I reinstall webUI 

 Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  D:\StableDiffusion\Python\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  D:\StableDiffusion\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers
 i   Arguments are now: --xformers
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.0
Commit hash: e5bb35299c0af5dbab461d46aa2b45f6c8996f76
Installing requirements

Installing requirements 1 for Infinite-Zoom

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --autolaunch --xformers
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\StableDiffusion\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
dirname:  D:\StableDiffusion\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable)': 'D:\\StableDiffusion\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-localization-zh_Hans-master\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing)': 'D:\\StableDiffusion\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-localization-zh_Hans-master\\localizations\\zh-Hans (Testing).json'}
2023-07-09 23:23:59,283 - ControlNet - INFO - ControlNet v1.1.220
ControlNet preprocessor location: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-09 23:23:59,470 - ControlNet - INFO - ControlNet v1.1.220
sd-webui-prompt-all-in-one background API service started successfully.
2023-07-09 23:24:06,262 - roop - INFO - roop v0.0.2
2023-07-09 23:24:06,262 - roop - INFO - roop v0.0.2
Loading weights [4199bcdd14] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\revAnimated_v122.safetensors
patched in extra network ui page: deltas
patched in extra network: deltas
Creating model from config: D:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
*Deforum ControlNet support: enabled*
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0):
Model loaded in 6.9s (load weights from disk: 2.0s, create model: 0.8s, apply weights to model: 1.2s, apply half(): 1.1s, move model to device: 1.6s, calculate empty prompt: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 43.7s (import torch: 5.9s, import gradio: 2.6s, import ldm: 1.0s, other imports: 3.0s, setup codeformer: 0.1s, load scripts: 18.4s, create ui: 8.0s, gradio launch: 4.4s).
preload_extensions_git_metadata for 35 extensions took 11.55s
*** Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\sam.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\sam.py", line 785, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range

---
*** Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.91it/s]
*** Error running postprocess_batch: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.34it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  7.02it/s]

**Comment by Gourieff** [comment]
You need to disable "SD-CN-Animation" extension

**Comment by ylmalta** [comment]
> I dont have  "SD-CN-Animation" extension, while I uninstall animatior extension ,still not working,bro

To create a public link, set `share=True` in `launch()`.
Startup time: 238.2s (import torch: 6.2s, import gradio: 2.8s, import ldm: 1.0s, other imports: 2.6s, setup codeformer: 0.2s, load scripts: 19.5s, initialize extra networks: 193.6s, create ui: 8.0s, gradio launch: 4.2s).
preload_extensions_git_metadata for 32 extensions took 5.92s
*** Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\sam.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\sam.py", line 785, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything-1.6.0\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range

---
*** Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.86it/s]
*** Error running postprocess_batch: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  2.85it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:05<00:00,  6.92it/s]

**Comment by ylmalta** [comment]
these are the estension all I had 
stable-diftuslon-webul-localization-zh Hans-master
stable-diffusion-webui-depthmap-script
Stable-Diffusion-Webui-Civitai-Helper
sd-webui-txt-img-to-3d-model
sd-webui-stablesr
sd-webui-segment-anything-1.60
sd-webui-roop
sd-webui-prompt-all-in-one-main
sd-webui-mov2mov
sd-webui-inpaint-anything-main
sd-webui-inpaint-anything
sd-webui-controlnet
sd-webui-bilingual-localization
infinite-zoom-automatic1111-webui
Hypernetwork-MonkeyPatch-Extension
gif2gif
ffmpeg
deforum-stable-diffusion
deforum-for-automatic1111-webui
custom-diffusion-webui
canvas-zoom
ABG extension
a1111-sd-webui-tagcomplete-main

**Comment by ylmalta** [comment]
[scripts.zip](https://github.com/s0md3v/sd-webui-roop/files/12004077/scripts.zip)
this is my scripts, is there anything wrong with it ?
***** Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'**

**Comment by glucauze** [comment]
It shouldn't happen. There seems to be a problem loading the UI. The parameters of the process function are passed by SD and are in fact interface components. You should try stopping SD and relaunching it.

**Comment by swumagic** [comment]
me too。txt 2 img can run normally And can replace the face normally。but img 2 img Not working, a bunch of error messages，Show a bunch of BUG。

**Comment by ylmalta** [comment]
> me too。txt 2 img can run normally And can replace the face normally。but img 2 img Not working, a bunch of error messages，Show a bunch of BUG。

seems like conflicts with one of the extension, as I reinstall with a pure SD only with roof extension , does work this time

**Comment by ylmalta** [comment]
> seems like conflicts with one of the extension, as I reinstall with a pure SD only with roof extension , does work this time

seems like conflicts with one of the extension, as I reinstall with a pure SD only with roof extension , does work this time

**Comment by swumagic** [comment]
controlnet？how to solve it? I turned off the Sd-c-n and TXT 2VIDIO plug-in expansion according to other people's methods, and it didn't work

> > 似乎与其中一个扩展冲突，因为我仅使用屋顶扩展使用纯 SD 重新安装，这次确实有效
> 
> 似乎与其中一个扩展冲突，因为我仅使用屋顶扩展使用纯 SD 重新安装，这次确实有效

**Comment by swumagic** [comment]
> > 似乎与其中一个扩展冲突，因为我只使用屋顶扩展使用纯SD重新安装，这次确实有效
> 
> 似乎与其中一个扩展冲突，因为我只使用屋顶扩展使用纯SD重新安装，这次确实有效



> > me too。txt 2 img can run normally And can replace the face normally。but img 2 img Not working, a bunch of error messages，Show a bunch of BUG。
> 
> seems like conflicts with one of the extension, as I reinstall with a pure SD only with roof extension , does work this time
The previous version was fine, it seems that the problem came after the latest update

**Comment by swumagic** [comment]
I turned off the Sd-c-n plug-in expansion is ok
