### ISSUE TITLE
Face and general image are clear and sharp, but edges are pixilated

### ISSUE THREAD

**Issue by waelmansourx** [s0md3v/sd-webui-roop#159]
![image](https://github.com/s0md3v/sd-webui-roop/assets/121588802/c8ca01b1-e9fb-4e67-940a-4b900aafcc62)

**Comment by glucauze** [comment]
You might try https://github.com/s0md3v/sd-webui-roop/pull/152 with upscaled_inswapper enabled in sd roop settings (global settings). You can choose LDSR as inswapper upscaller. It might give better results as it upscale the face before merging it. It's experimental but i have got better results with it.
