### ISSUE TITLE
img2img Not working, a bunch of error messages，Show a bunch of BUG。

### ISSUE THREAD

**Issue by swumagic** [s0md3v/sd-webui-roop#160]
extension conflict.Here are args received by ControlNet: ().
*** Error running process: M:\SD\sdwebui\extensions\a1111-sd-webui-segment-anything\scripts\sam.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "M:\SD\sdwebui\extensions\a1111-sd-webui-segment-anything\scripts\sam.py", line 785, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "M:\SD\sdwebui\extensions\a1111-sd-webui-segment-anything\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "M:\SD\sdwebui\extensions\a1111-sd-webui-segment-anything\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "M:\SD\sdwebui\extensions\a1111-sd-webui-segment-anything\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "M:\SD\sdwebui\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['M:\\SD\\sdwebui\\launch.py', '--medvram',           │ │
    │ │             │ '--theme', 'dark', '--xformers', '--api',             │ │
    │ │             │ '--autolaunch']                                       │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ 8k, best quality, masterpiece,1girl,              │ │
    │ │ negative_prompt │ ugly,bad_anatomy,bad_hands,extra_hands,missing_f… │ │
    │ │                 │ hand,more than two hands,well proportioned        │ │
    │ │                 │ hands,more than two legs,unclear                  │ │
    │ │                 │ eyes,missing_arms,mutilated,extra limbs,extra     │ │
    │ │                 │ legs,cloned face,fused fingers,extra_digit,       │ │
    │ │                 │ fewer_digits,extra_digits,jpeg_artifacts,signatu… │ │
    │ │                 │ image, Vague                                      │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 648                                               │ │
    │ │          height │ 806                                               │ │
    │ │    sampler_name │ Euler a                                           │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ chilloutmix_NiPrunedFp32Fix.safetensors           │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors          │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ M:\SD\sdwebui\extensions\adetailer\adetailer\traceback.py:136 in    │ │
    │ │ wrapper                                                             │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py:500 in     │ │
    │ │ process                                                             │ │
    │ │                                                                     │ │
    │ │   497 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   498 │   │   │   return                                            │ │
    │ │   499 │   │                                                         │ │
    │ │ > 500 │   │   if self.is_ad_enabled(*args_):                        │ │
    │ │   501 │   │   │   arg_list = self.get_args(p, *args_)               │ │
    │ │   502 │   │   │   extra_params = self.extra_params(arg_list)        │ │
    │ │   503 │   │   │   p.extra_generation_params.update(extra_params)    │ │
    │ │                                                                     │ │
    │ │ M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py:171 in     │ │
    │ │ is_ad_enabled                                                       │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running process: M:\SD\sdwebui\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 5 required positional arguments: 'active', 'tileX', 'tileY', 'startStep', and 'stopStep'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\batch-face-swap\scripts\batch_face_swap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 57 required positional arguments: 'enabled', 'mainTab', 'overridePrompt', 'bfs_prompt', 'bfs_nprompt', 'overrideSampler', 'sd_sampler', 'overrideModel', 'sd_model', 'overrideDenoising', 'denoising_strength', 'overrideMaskBlur', 'mask_blur', 'overridePadding', 'inpaint_full_res_padding', 'overrideSeed', 'overrideSteps', 'steps', 'overrideCfgScale', 'cfg_scale', 'overrideSize', 'bfs_width', 'bfs_height', 'input_path', 'searchSubdir', 'divider', 'howSplit', 'saveMask', 'output_path', 'saveToOriginalFolder', 'viewResults', 'saveNoFace', 'onlyMask', 'invertMask', 'singleMaskPerImage', 'countFaces', 'maskWidth', 'maskHeight', 'keepOriginalName', 'pathExisting', 'pathMasksExisting', 'output_pathExisting', 'selectedTab', 'faceDetectMode', 'face_x_scale', 'face_y_scale', 'minFace', 'multiScale', 'multiScale2', 'multiScale3', 'minNeighbors', 'mpconfidence', 'mpcount', 'debugSave', 'optimizeDetect', 'loadGenParams', and 'rotation_threshold'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 18 required positional arguments: 'is_enabled', 'is_combinatorial', 'combinatorial_batches', 'is_magic_prompt', 'is_feeling_lucky', 'is_attention_grabber', 'min_attention', 'max_attention', 'magic_prompt_length', 'magic_temp_value', 'use_fixed_seed', 'unlink_seed_from_prompt', 'disable_negative_prompt', 'enable_jinja_templates', 'no_image_generation', 'max_generations', 'magic_model', and 'magic_blocklist_regex'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\sd-extension-steps-animation\scripts\steps_animation.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 12 required positional arguments: 'is_enabled', 'codec', 'interpolation', 'duration', 'skip_steps', 'last_frame_duration', 'debug', 'run_incomplete', 'tmp_delete', 'out_create', 'tmp_path', and 'out_path'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-10 23:54:50,013 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: M:\SD\sdwebui\extensions\sd-webui-cutoff\scripts\cutoff.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 8 required positional arguments: 'enabled', 'targets_', 'weight', 'disable_neg', 'strong', 'padding', 'intp', and 'debug'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\stable-diffusion-NPW\scripts\npw.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 1 required positional argument: 'weight'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: ComposableLoraScript.process() missing 7 required positional arguments: 'enabled', 'opt_composable_with_step', 'opt_uc_text_model_encoder', 'opt_uc_diffusion_model', 'opt_plot_lora_weight', 'opt_single_no_uc', and 'opt_hires_step_as_global'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: M:\SD\sdwebui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 5 required positional arguments: 'enabled', 'raw_divisions', 'raw_positions', 'raw_weights', and 'raw_end_at_step'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running before_process_batch: M:\SD\sdwebui\extensions\sd-face-editor\scripts\face_editor_extension.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 482, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
    TypeError: FaceEditorExtension.before_process_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process_batch: M:\SD\sdwebui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
    TypeError: Script.process_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'sched_val'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process_batch: M:\SD\sdwebui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "M:\SD\sdwebui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 190, in process_batch
        if not args[0]:
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_batch: M:\SD\sdwebui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_batch: M:\SD\sdwebui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'sched_val'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_batch: M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_image: M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "M:\SD\sdwebui\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['M:\\SD\\sdwebui\\launch.py', '--medvram',           │ │
    │ │             │ '--theme', 'dark', '--xformers', '--api',             │ │
    │ │             │ '--autolaunch']                                       │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ 8k, best quality, masterpiece,1girl,              │ │
    │ │ negative_prompt │ ugly,bad_anatomy,bad_hands,extra_hands,missing_f… │ │
    │ │                 │ hand,more than two hands,well proportioned        │ │
    │ │                 │ hands,more than two legs,unclear                  │ │
    │ │                 │ eyes,missing_arms,mutilated,extra limbs,extra     │ │
    │ │                 │ legs,cloned face,fused fingers,extra_digit,       │ │
    │ │                 │ fewer_digits,extra_digits,jpeg_artifacts,signatu… │ │
    │ │                 │ image, Vague                                      │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 648                                               │ │
    │ │          height │ 806                                               │ │
    │ │    sampler_name │ Euler a                                           │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ chilloutmix_NiPrunedFp32Fix.safetensors           │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors          │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ M:\SD\sdwebui\extensions\adetailer\adetailer\traceback.py:136 in    │ │
    │ │ wrapper                                                             │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py:596 in     │ │
    │ │ postprocess_image                                                   │ │
    │ │                                                                     │ │
    │ │   593 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   594 │   │   │   return                                            │ │
    │ │   595 │   │                                                         │ │
    │ │ > 596 │   │   if not self.is_ad_enabled(*args_):                    │ │
    │ │   597 │   │   │   return                                            │ │
    │ │   598 │   │                                                         │ │
    │ │   599 │   │   p._ad_idx = getattr(p, "_ad_idx", -1) + 1             │ │
    │ │                                                                     │ │
    │ │ M:\SD\sdwebui\extensions\adetailer\scripts\!adetailer.py:171 in     │ │
    │ │ is_ad_enabled                                                       │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running postprocess_image: M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: M:\SD\sdwebui\extensions\batch-face-swap\scripts\batch_face_swap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 57 required positional arguments: 'enabled', 'mainTab', 'overridePrompt', 'bfs_prompt', 'bfs_nprompt', 'overrideSampler', 'sd_sampler', 'overrideModel', 'sd_model', 'overrideDenoising', 'denoising_strength', 'overrideMaskBlur', 'mask_blur', 'overridePadding', 'inpaint_full_res_padding', 'overrideSeed', 'overrideSteps', 'steps', 'overrideCfgScale', 'cfg_scale', 'overrideSize', 'bfs_width', 'bfs_height', 'input_path', 'searchSubdir', 'divider', 'howSplit', 'saveMask', 'output_path', 'saveToOriginalFolder', 'viewResults', 'saveNoFace', 'onlyMask', 'invertMask', 'singleMaskPerImage', 'countFaces', 'maskWidth', 'maskHeight', 'keepOriginalName', 'pathExisting', 'pathMasksExisting', 'output_pathExisting', 'selectedTab', 'faceDetectMode', 'face_x_scale', 'face_y_scale', 'minFace', 'multiScale', 'multiScale2', 'multiScale3', 'minNeighbors', 'mpconfidence', 'mpcount', 'debugSave', 'optimizeDetect', 'loadGenParams', and 'rotation_threshold'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: M:\SD\sdwebui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: M:\SD\sdwebui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: M:\SD\sdwebui\extensions\sd-extension-steps-animation\scripts\steps_animation.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 12 required positional arguments: 'is_enabled', 'codec', 'interpolation', 'duration', 'skip_steps', 'last_frame_duration', 'debug', 'run_incomplete', 'tmp_delete', 'out_create', 'tmp_path', and 'out_path'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: M:\SD\sdwebui\extensions\sd-face-editor\scripts\face_editor_extension.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: FaceEditorExtension.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-10 23:55:01,677 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-07-10 23:55:01,683 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-07-10 23:55:36,812 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-07-10 23:55:36,817 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-07-10 23:55:46,470 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an

**Comment by swumagic** [comment]
txt 2 img can run normally  And can replace the face normally。but img 2 img Not working, a bunch of error messages，Show a bunch of BUG。

**Comment by s0md3v** [comment]
The error doesn't seem to be related sd-webui-roop.

**Comment by swumagic** [comment]
> 该错误似乎与 sd-webui-roop 无关。

Dear author, how to solve it? I turned off the Sd-c-n and TXT 2VIDIO plug-in expansion according to other people's methods, and it didn't work

**Comment by XTRMsavage** [comment]
I am getting this error 
"*** Error running postprocess_image: D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-v14\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'"

**Comment by swumagic** [comment]
I turned off the Sd-c-n  plug-in expansion ok

**Comment by swumagic** [comment]
> I am getting this error "*** Error running postprocess_image: D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py Traceback (most recent call last): File "D:\stable-diffusion-v14\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image script.postprocess_image(p, pp, *script_args) File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image result: ImageResult = swap_face( File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face result = face_swapper.get(result, target_face, source_face) AttributeError: 'NoneType' object has no attribute 'get'"

If you encounter 'NoneType' object has no attribute 'get' error, download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside <webui_dir> /models/roop/ directory.
