### ISSUE TITLE
Script 'roop' not found

### ISSUE THREAD

**Issue by liuzhongh** [s0md3v/sd-webui-roop#171]
curl -X 'POST' \
'http://ip:7860/sdapi/v1/txt2img' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
    "enable_hr": false,
    "denoising_strength": 0,
    "firstphase_width": 0,
    "firstphase_height": 0,
    "hr_scale": 2,
    "hr_upscaler": "string",
    "hr_second_pass_steps": 0,
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "hr_sampler_name": "string",
    "hr_prompt": "",
    "hr_negative_prompt": "",
    "prompt": "1girl",
    "styles": [
    "string"
    ],
    "seed": -1,
    "subseed": -1,
    "subseed_strength": 0,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "sampler_name": "DPM++ SDE Karras",
    "batch_size": 1,
    "n_iter": 1,
    "steps": 30,
    "cfg_scale": 7,
    "width": 512,
    "height": 512,
    "restore_faces": true,
    "tiling": false,
    "do_not_save_samples": false,
    "do_not_save_grid": false,
    "negative_prompt": "lowres",
    "eta": 0,
    "s_min_uncond": 0,
    "s_churn": 0,
    "s_tmax": 0,
    "s_tmin": 0,
    "s_noise": 1,
    "override_settings": {},
    "override_settings_restore_afterwards": true,
    "script_args":[],
    "sampler_index": "DPM++ SDE Karras",
    "script_name": "roop",
    "send_images": false,
    "send_images_url": true,
    "save_images": false,
    "alwayson_scripts": {
        "roop": {
            "args":[
                "base64string"
                true,
                0,
                "/path/to/stable diffussion/models/roop/inswapper_128.onnx",
                "CodeFormer",
                1,
                "R-ESRGAN 4x+",
                1,
                1,
                false,
                true
            ]
        }
    }

}

When I make an API call with the above content as a parameter, it is reported that error: Script 'roop' not found.

**Comment by Gourieff** [comment]
You can see if the script is enabled or not and what call-name it has
http://<server_ip>:7860/sdapi/v1/script-info

**Comment by liuzhongh** [comment]
> You can see if the script is enabled or not and what call-name it has http://<server_ip>:7860/sdapi/v1/script-info

http://ip:7860/sdapi/v1/scripts

**Comment by liuzhongh** [comment]
Found the source of the problem. It can now be used normally.
