### ISSUE TITLE
Faceswap.py Error 

### ISSUE THREAD

**Issue by killamonis** [s0md3v/sd-webui-roop#176]
Been trying to use roop through the api call, and have been getting the following error 
```
*** Error running process: /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswappy
Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/modules/scripts.py", line 474, in process script.process(p,
*script_args)
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py",line 154, in process
int(x) for × in faces_index.strip(",").split(",") if x. isnumericO)
AttributeError: 'int' object has no attribute 'strip'
```

this is a snippet of the api call im using 
```
"alwayson_scripts": {
     "roop": {
                "args":[
                    "",
                    true,
                    0,
                    "workspace/stable-diffusion-webui/models/roop/inswapper_128.onnx",
                    "CodeFormer",
                    1,
                    "ESRGAN_4x",
                    1,
                    1,
                    false,
                    true
                ]
    }
```

**Comment by liuzhongh** [comment]
"alwayson_scripts": {
     "roop": {
                "args":[
                    "",
                    true,
                    0,**//This value must be a string, such as "0"**
                    "workspace/stable-diffusion-webui/models/roop/inswapper_128.onnx",
                    "CodeFormer",
                    1,
                    "ESRGAN_4x",
                    1,
                    1,
                    false,
                    true
                ]
    }

**Comment by killamonis** [comment]
> "alwayson_scripts": { "roop": { "args":[ "", true, 0,**//This value must be a string, such as "0"** "workspace/stable-diffusion-webui/models/roop/inswapper_128.onnx", "CodeFormer", 1, "ESRGAN_4x", 1, 1, false, true ] }

Thank you this worked. But now I'm getting an error saying there is no model file, and it's checking for one in the scripts folder for some reason. 
```
*** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/modules/scripts.py", line 514, in postprocess_image
script.postprocess_image(p, pP, *script_args)
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py",line 184, in postprocess_image
result: ImageResult = swap_face(
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 127, in swap_face
face_swapper = getFaceSwapModel(model_path)
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py",line 40, in getFaceSwapModel
FS_MODEL = insightface.model_zoo.get_model(model_path, providers-providers)
File "/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py",line 91, in get_
assert osp.exists(model_file), 'model_file % should exist "%model_file
AssertionError: model_file /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/inswapper_128.on should exist
```
I have a model file in '/workspace/stable-diffusion-webui/models/roop/inswapper_128.onnx'

**Comment by killamonis** [comment]
> "alwayson_scripts": { "roop": { "args":[ "", true, 0,**//This value must be a string, such as "0"** "workspace/stable-diffusion-webui/models/roop/inswapper_128.onnx", "CodeFormer", 1, "ESRGAN_4x", 1, 1, false, true ] }

thanks this worked!
