### ISSUE TITLE
Прическа и одежда ?

### ISSUE THREAD

**Issue by naitedj** [s0md3v/sd-webui-roop#201]
Tell me, what if you do the same for hair and clothes? I don't know if this is possible. But then there would be complete control over the character. It is very difficult to make the desired hairstyle, especially if you need several arts.

**Comment by Gourieff** [comment]
For desirable hair and clothes you can use LoRA or InstructPix2Pix or even you can achieve what you want just with a specific prompt

**Comment by naitedj** [comment]
It's a pity) I would like it to be just as simple, just the right hairstyle or clothes. Learning takes time and computer power. Promt... you can display the right one for hours) In any case, thanks for such a plugin.
