### ISSUE TITLE
Where is the "roop" drop-down menu?

### ISSUE THREAD

**Issue by Zalmighty** [s0md3v/sd-webui-roop#22]
I Have installed sd-webui-roop successfully, but I don`t know where is the "roop" drop-down menu...
![image](https://github.com/s0md3v/sd-webui-roop/assets/23116994/9053c11d-7958-420d-bf3c-e05a9e676170)

**Comment by Zalmighty** [comment]
Where is it
![image](https://github.com/s0md3v/sd-webui-roop/assets/23116994/4e812dbb-f5ba-4ebb-a5c3-bfb6804516ac)

**Comment by s0md3v** [comment]
If you have no errors, it should be right below controlnet.
