### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'.  // I'm using a mac M1 

### ISSUE THREAD

**Issue by khawlyai** [s0md3v/sd-webui-roop#225]
cant seem to be able to access the dropdown menu in the UI

File "/Users/robertkhawli/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

thank you

**Comment by khawlyai** [comment]
I even reinstalled all from scratch and had the same result. Nothing on Google search helps when it comes to M1 Mac

**Comment by Gourieff** [comment]
@khawlyai you can use my instruction https://github.com/Gourieff/sd-webui-reactor/issues/42 with my [fork](https://github.com/Gourieff/sd-webui-reactor)
Works perfectly with Mac M-series

**Comment by khawlyai** [comment]
thank you so so so so much. issue solved. keep it up.
