### ISSUE TITLE
Conforming dependency specifiers

### ISSUE THREAD

**Issue by Phartona** [s0md3v/sd-webui-roop#234]
Over two months ago roop still worked fine for me. Had to reinstall it today and its now asking for conforming dependecy specifiers that have to be added by the author.
```
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (d:\programme\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (d:\programme\stablediffusion\stable-diffusion-webui\venv\lib\site-packages)
*** DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
*** ERROR: Could not install packages due to an OSError: [WinError 5] Zugriff verweigert: 'D:\\Programme\\StableDiffusion\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
*** Check the permissions.
```

**Comment by Gourieff** [comment]
> DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier
It's not the error that cause an issue, it's just a deprecation
The reason is that you have a temp installation folder (~rotobuf) of the protobuf package that cannot be rewrite by OS during a new installation attempt of this package
Try this solution: https://github.com/Gourieff/sd-webui-reactor#vii-importerror-cannot-import-name-builder-from-googleprotobufinternal

**Comment by Phartona** [comment]
Not that well versed with these things or logs so thanks for the answer. Sadly the error still occurs. It does add the tab now to the A1111 UI and also says in the UI that the installation was a success. Probably will have to try the 8th troubleshooting section under the link you sent since the logs mention that it fails to install insightface.

**Comment by Phartona** [comment]
ended up swapping to reactor and following their installation steps. No idea if the same installation steps would help with roop
