### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Fillllllllllll** [s0md3v/sd-webui-roop#251]
My roop is installed and i can see it in txt2img and img2img but I there is no faceswap results (no nswf).
I have this type of issue:

Error running postprocess_batch: /content/cagliostro-colab-ui/extensions/sd-webui-roop-main/scripts/faceswap.py
Traceback (most recent call last):
  File "/content/cagliostro-colab-ui/modules/scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/content/cagliostro-colab-ui/extensions/sd-webui-roop-main/scripts/faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "/content/cagliostro-colab-ui/extensions/sd-webui-roop/scripts/swapper.py", line 132, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

Could you help to solve it, please?

**Comment by paboum** [comment]
See https://github.com/deepinsight/insightface/issues/2294

**Comment by Fillllllllllll** [comment]
I'm using SD with google colab notebook
Should i put "inswapper_128" inside Scripts folder?

**Comment by paboum** [comment]
> + If you encounter `'NoneType' object has no attribute 'get'` error, download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside `<webui_dir>/models/roop/` directory.

The only question is where to take that file from since roop devs decided to go crazy and hid it. One possible location is Google Drive as linked in the discussion I linked above.

**Comment by Fillllllllllll** [comment]
Thank you, it helped!
