### ISSUE TITLE
Says it's installed, no menu

### ISSUE THREAD

**Issue by DarksealStudios** [s0md3v/sd-webui-roop#26]
It says it's installed but there is no drop down menu. I do have others; face swap, batch face swap 0.0.7
When it didnt seem to install from the extension tab I followed the link to see I needed to pip install insightface==0.7.3
Did doing these two things backwards make the tab not show up in the gui? I've relaunched, still nothing.

**Comment by s0md3v** [comment]
I have no idea what you guys are talking about. When I saw your issue and a couple more similar ones, I deleted my extension and the model. Then, I installed it from scratch using AUTOMATIC webui's install from URL option and it worked as expected.

**Comment by DarksealStudios** [comment]
why close this like the issue is solved? So, what you are saying is, delete the extension and install again? Why not just say that instead of pretending like we are making it up?

**Comment by s0md3v** [comment]
What I am saying is that I don't care about what installation problems each person is having, the extension works for me 0 I just tested it after you created this issue.

I am only responsible for the bugs inside this software. Google the rest.

**Comment by DarksealStudios** [comment]
I see. Well, for the next person who DOES care, you MUST first : pip install insightface==0.7.3

then install the extension. Deleting and reinstalling the extension DID fix my issue of the tab not showing up after the pip install.

**Comment by s0md3v** [comment]
@DarksealStudios the insightface part is already mentioned in the readme btw.

**Comment by DarksealStudios** [comment]
@s0md3v , no one will know to do this first when simply going to the extensions tab to install your extension. If a person doesn't "know" to come to your readme before actually installing it.... then what? Then they get met with

"What I am saying is that I don't care about what installation problems each person is having, the extension works for me 0 I just tested it after you created this issue."

**Comment by alenknight** [comment]
$10 says the lead dev won't be supporting this for long. lol.  
tho i do hope i'm wrong.

**Comment by DarksealStudios** [comment]
it's not great with micro faces, seems like there is a threshold for face detection with no way to adjust @alenknight . It also seems to drop the face for a few frames and then pick it back up again. I was doing a batch in auto1111 testing it out. Wish there were some more settings but with love like my first reply i can only guess the answers to my question will include gtfo.

**Comment by s0md3v** [comment]
@alenknight, I have no plans of abandoning this project. However, I don't have enough bandwidth to respond to every env specific issue.

"my opencv is giving me errors", okay, use google and good luck, let me know when something in MY CODE breaks.
