### ISSUE TITLE
Extensions tab does not appear in webUI

### ISSUE THREAD

**Issue by Siziff** [s0md3v/sd-webui-roop#276]
The extensions tab does not appear but it is in the list of extensions.

![image](https://github.com/s0md3v/sd-webui-roop/assets/42972554/303f31b1-c56a-4b92-bf72-df42f3840579)  

 I reinstalled the extension but it didn't help.

![image](https://github.com/s0md3v/sd-webui-roop/assets/42972554/325fea2c-38a9-46ff-9442-0b7ca6d6d51f)

**Comment by cuongloveit** [comment]
I got the same

**Comment by lavalbuena357** [comment]
> The extensions tab does not appear but it is in the list of extensions.
> 
> ![image](https://user-images.githubusercontent.com/42972554/279078067-303f31b1-c56a-4b92-bf72-df42f3840579.png)
> 
> I reinstalled the extension but it didn't help.
> 
> ![image](https://user-images.githubusercontent.com/42972554/279077578-325fea2c-38a9-46ff-9442-0b7ca6d6d51f.png)

On Windows, download and install [Visual Studio](https://visualstudio.microsoft.com/downloads/). During the install, make sure to include the Python and C++ packages.

Run this command: pip install insightface==0.7.3

**Comment by bobba84** [comment]
Hello, can you please clarify the " include the Python and C++ packages." - there is no option I can see for Python?? Thank you!

**Comment by sajjadalis** [comment]
I'm experiencing the same problem. I had trouble building insightface, but it was resolved after I installed the Visual Studio C++ tools. There are no errors now, but I still can't see the roop in WebUI.
