### ISSUE TITLE
Im getting this error, please help, thanks!

### ISSUE THREAD

**Issue by gokuchiku** [s0md3v/sd-webui-roop#30]
![roop final error](https://github.com/s0md3v/sd-webui-roop/assets/136511176/6c6a70e1-0a7b-4a74-8166-6dc5ce2866b9)
using nvidia 1060gigs
windows 10
automatic1111
command arguments are medvram, xformers and no half vae

**Comment by s0md3v** [comment]
There are only two possible solutions and if none of them work, I can't help you.

1. Delete the model and download it manually from the link given in readme.
2. Try upgrading/downgrading protobuf python library.
