### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by poorshu** [s0md3v/sd-webui-roop#33]
Error calling: D:\AI\extensions\sd-webui-roop\scripts\faceswap.py/ui
Traceback (most recent call last):
  File "D:\AI\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "D:\AI\extensions\sd-webui-roop\scripts\faceswap.py", line 64, in ui
    models = get_models()
  File "D:\AI\extensions\sd-webui-roop\scripts\faceswap.py", line 21, in get_models
    models = glob.glob(models_path)
UnboundLocalError: local variable 'models_path' referenced before assignment
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Ling-APE** [comment]
> ![image](https://user-images.githubusercontent.com/135423980/247614818-a32355b8-1fd5-4cc8-aece-3a1cdafdecb1.png)

same here

**Comment by poorshu** [comment]
> > ![image](https://user-images.githubusercontent.com/135423980/247614818-a32355b8-1fd5-4cc8-aece-3a1cdafdecb1.png)
> 
> 我也是

rollback version ccca35e
回退版本ccca35e

**Comment by icepickgit** [comment]
Just edit faceswap.py and swap lines 21 and 22
From this:
![Screenshot 2023-06-21 122137](https://github.com/s0md3v/sd-webui-roop/assets/42625310/95fb2423-531a-408f-9446-2b7bbc2b03d4)

To This:
![Screenshot 2023-06-21 122108](https://github.com/s0md3v/sd-webui-roop/assets/42625310/2b9a4358-e6e1-4794-bcfe-1cf5c898cc50)

**Comment by poorshu** [comment]
> Just edit faceswap.py and swap lines 21 and 22 From this: ![Screenshot 2023-06-21 122137](https://user-images.githubusercontent.com/42625310/247621378-95fb2423-531a-408f-9446-2b7bbc2b03d4.png)
> 
> To This: ![Screenshot 2023-06-21 122108](https://user-images.githubusercontent.com/42625310/247621471-2b9a4358-e6e1-4794-bcfe-1cf5c898cc50.png)

谢谢大佬，已经正常工作了。
Thank you boss, it's working fine now

**Comment by alenknight** [comment]
i had to do this too.... looks like it was explicitly changed around in today's patch to where it broke.

**Comment by alieverlove** [comment]
> Just edit faceswap.py and swap lines 21 and 22 From this: ![Screenshot 2023-06-21 122137](https://user-images.githubusercontent.com/42625310/247621378-95fb2423-531a-408f-9446-2b7bbc2b03d4.png)
> 
> To This: ![Screenshot 2023-06-21 122108](https://user-images.githubusercontent.com/42625310/247621471-2b9a4358-e6e1-4794-bcfe-1cf5c898cc50.png)

thnks bro

**Comment by s0md3v** [comment]
This issue has been fixed, my fault.

**Comment by hiten46** [comment]
def get_models():
    models_path = os.path.join(scripts.basedir(), "models/roop/*")
    models = glob.glob(models_path)
    models = [x for x in models if x.endswith(".onnx") or x.endswith(".pth")]
    return models


IS MY LINE 23 MISSING???


I AM GETTING THIS ERROR 

Error running postprocess_batch: C:\Users\VIPER PC\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
