### ISSUE TITLE
AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by Salexxxx23** [s0md3v/sd-webui-roop#37]
Hello.
Installed Visual Studio (Like everything you need, according to two youtube videos)
Installed insightface. He gave an error until he manually copied from users to the venv//site-packages folder in the stable diffusion folder. Install ifnude
The root tab appeared, but at startup, it gives such errors
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch              release_candidate -> FETCH_HEAD
Already up to date.
venv "venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.4.0-RC
Commit hash: 3b11f17a374520e493e120e7f47443acd97393c8
Installing requirements
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Launching Web UI with arguments: --autolaunch --xformers --theme=dark
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
2023-06-21 21:24:37,798 - roop - INFO - roop v0.0.2
2023-06-21 21:24:37,800 - roop - INFO - roop v0.0.2
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: tmp/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Loading weights [aba96b389d] from E:\amain\models\Stable-diffusion\mdjrny-v4.safetensors
*** Error calling: E:\amain\extensions\sd-webui-roop\scripts\faceswap.py/ui
    Traceback (most recent call last):
      File "E:\amain\modules\scripts.py", line 294, in wrap_call
        return func(*args, **kwargs)
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 64, in ui
        models = get_models()
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 21, in get_models
        models = glob.glob(models_path)
    UnboundLocalError: local variable 'models_path' referenced before assignment

---
*** Error calling: E:\amain\extensions\sd-webui-roop\scripts\faceswap.py/ui
    Traceback (most recent call last):
      File "E:\amain\modules\scripts.py", line 294, in wrap_call
        return func(*args, **kwargs)
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 64, in ui
        models = get_models()
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 21, in get_models
        models = glob.glob(models_path)
    UnboundLocalError: local variable 'models_path' referenced before assignment

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\amain\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Startup time: 8.0s (import torch: 1.3s, import gradio: 1.0s, import ldm: 0.4s, other imports: 0.8s, opts onchange: 0.7s, load scripts: 2.7s, create ui: 0.6s, gradio launch: 0.3s).
DiffusionWrapper has 859.52 M params.
preload_extensions_git_metadata for 11 extensions took 0.53s
Loading VAE weights specified in settings: E:\amain\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0):
Model loaded in 4.9s (load weights from disk: 0.8s, create model: 0.5s, apply weights to model: 0.7s, apply half(): 1.1s, load VAE: 0.2s, move model to device: 1.5s)
--------------------------------------------------------------------------------------------------------------------------------------------------
And when I launch "roop"

*** Error running process: E:\amain\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\amain\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  5.68it/s]
*** Error running postprocess_batch: E:\amain\extensions\sd-webui-roop\scripts\faceswap.py6/16 [00:02<00:00,  7.05it/s]
    Traceback (most recent call last):
      File "E:\amain\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: E:\amain\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\amain\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\amain\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.58it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.05it/s]

**Comment by Kinderheim512** [comment]
Same for me

**Comment by Salexxxx23** [comment]
I also swapped the lines in places, it seems to have worked
https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721

**Comment by bsenftner** [comment]
I swapped the lines as indicated by https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721 but am still seeing AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by ronbere** [comment]
> I swapped the lines as indicated by [#33 (comment)](https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721) but am still seeing AttributeError: 'FaceSwapScript' object has no attribute 'enable'

same here

**Comment by FoneCheck** [comment]
I also swapped the lines in places, it seems to have worked for me as well
https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721

**Comment by s0md3v** [comment]
This has been fixed.

**Comment by SteveM50** [comment]
not yet

 Error running postprocess_image: D:\Users\User\stable-diffusion-webui2\webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\Users\User\stable-diffusion-webui2\webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\Users\User\stable-diffusion-webui2\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by JScottMacD** [comment]
> not yet
> 
> Error running postprocess_image: D:\Users\User\stable-diffusion-webui2\webui\extensions\sd-webui-roop\scripts\faceswap.py Traceback (most recent call last): File "D:\Users\User\stable-diffusion-webui2\webui\modules\scripts.py", line 514, in postprocess_image script.postprocess_image(p, pp, *script_args) File "D:\Users\User\stable-diffusion-webui2\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image if self.enable and self.swap_in_generated: AttributeError: 'FaceSwapScript' object has no attribute 'enable'

Yep got the exact same this morning, was working perfectly last night

**Comment by Vrahel88** [comment]
Was fine yesterday. Today I get this:

Error running postprocess_batch: C:\Stable Diffusion\webui\extensions\sd-webui-roop\scripts\faceswap.py, 11.14it/s]
    Traceback (most recent call last):
      File "C:\Stable Diffusion\webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "C:\Stable Diffusion\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: C:\Stable Diffusion\webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Stable Diffusion\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by loccisimone88** [comment]
Good morning fellas, I am having the same issue but I didn't understood how to fix it, someone can help me/us?

**Comment by kuschzzp** [comment]
> 

thank you,  disable Mov2Mov works for me

**Comment by kuschzzp** [comment]
> "Off" all your extensions and check it. If it works, "on" them one by one and find the that which conflict with Roop. Mine was "Mov2Mov". Cheers


thank you, disable Mov2Mov works for me

**Comment by loccisimone88** [comment]
Thank you guys, seems ti work now!

**Comment by FabienEphKa** [comment]
thank you, disable Mov2Mov works for me
