### ISSUE TITLE
 **UnboundLocalError on line 21 of the script**

### ISSUE THREAD

**Issue by designium** [s0md3v/sd-webui-roop#40]
Dear s0md3v,

I have encountered an `UnboundLocalError` in the script provided in the repository. The error is due to the use of an undefined local variable `models_path` on line 21:

```python
models = glob.glob(models_path)
```

This issue is caused because `models_path` is not defined before this line of code is executed. However, I noticed that `models_path` is defined later on in the script:

```python
models_path = os.path.join(scripts.basedir(), "models/roop/*")
```

To fix this issue, I suggest moving the definition of `models_path` before its usage. Here is the corrected `get_models()` function:

```python
def get_models():
    models_path = os.path.join(scripts.basedir(), "models/roop/*")
    models = glob.glob(models_path)
    models += glob.glob(models_path)
    models = [x for x in models if x.endswith(".onnx") or x.endswith(".pth")]
    return models
```

This change has resolved the `UnboundLocalError` in my tests. I am reporting this so it might be helpful to others who face the same issue, and for a possible fix in a future update of the script.

Thank you for your attention to this matter.

Best regards

**Comment by designium** [comment]
I will leave you to close this issue so you are aware of it.

**Comment by s0md3v** [comment]
Fixed.
