### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by AidenMorgan07** [s0md3v/sd-webui-roop#42]
AttributeError: 'NoneType' object has no attribute 'get'

Please thats my code for error can't swap
What the solution?

**Comment by ToTheTopYo** [comment]
I had the same issue.
The solution was posted here
https://github.com/s0md3v/sd-webui-roop/issues/12#issuecomment-1599502177

**Comment by mostafablender** [comment]
Error running postprocess_batch: D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\modules\scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\faceswap.py", line 183, in postprocess_image
    result: ImageResult = swap_face(
  File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\swapper.py", line 134, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bugtig6351** [comment]
> Error running postprocess_batch: D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\faceswap.py Traceback (most recent call last): File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\modules\scripts.py", line 462, in postprocess_image script.postprocess_image(p, pp, *script_args) File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\faceswap.py", line 183, in postprocess_image result: ImageResult = swap_face( File "D:\Games\SSSSSSSSSSS\stable-diffusion-webui-master\extensions\sd-webui-roop\scripts\swapper.py", line 134, in swap_face result = face_swapper.get(result, target_face, source_face) AttributeError: 'NoneType' object has no attribute 'get'

1. download buffalo_l.zip from https://github.com/deepinsight/insightface/releases
2. unzip it into stable-diffusion-webui/models/roop

the files in `<webui_dir>/models/roop` should be like this
```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          DF5C06B8A0C12E422B2ED8947B8869FAA4105387F199C477AF038AA01F9A45CC       1k3d68.onnx
SHA256          F001B856447C413801EF5C42091ED0CD516FCD21F2D6B79635B1E733A7109DBF       2d106det.onnx
SHA256          5838F7FE053675B1C7A08B633DF49E7AF5495CEE0493C7DCF6697200B85B5B91       det_10g.onnx
SHA256          4FDE69B1C810857B88C64A335084F1C3FE8F01246C9A191B48C7BB756D6652FB       genderage.onnx
SHA256          E4A3F08C753CB72D04E10AA0F7DBE3DEEBBF39567D4EAD6DCE08E98AA49E16AF       inswapper_128.onnx
SHA256          4C06341C33C2CA1F86781DAB0E829F88AD5B64BE9FBA56E56BC9EBDEFC619E43       w600k_r50.onnx
```

**Comment by mostafablender** [comment]
thank you vey much
