### ISSUE TITLE
Feature Request - Enable use of roop's during "Extras" tab upscaling

### ISSUE THREAD

**Issue by remghoost** [s0md3v/sd-webui-roop#45]
Hello. Super neat extension.

I find that when I do my final 4x upscale with the Extras tab using CodeFormer, I lose a decent amount of the input face.

I see that there's an option to use an upscaler during generation, but is there any way to enable the use of roop while upscaling in the "Extras" tab? Essentially just have the dropdown that's in txt2img/img2img in the Extras tab as well.

I'd love to just automatically upscale every generation I make, but my 1060 6GB and I don't really have the resources (or the time) for that. haha.

**Comment by s0md3v** [comment]
roop uses a 128x128 pixels model, it is not a good idea to use after upscaling.

There are workarounds this problem but I don't want the tool to be any more complication than it needs to be.

**Comment by remghoost** [comment]
Ah. No worries. 
That makes sense.

I have an addendum question then, what is the purpose of the upscaler in roops....?
Is that just upscaling the input image?

**Comment by ToTheTopYo** [comment]
> Ah. No worries. That makes sense.
> 
> I have an addendum question then, what is the purpose of the upscaler in roops....? Is that just upscaling the input image?

It upscales the image as if you're using the upscaler in the extras tab.
