### ISSUE TITLE
It show Error "No module named 'insightface'" when I restart UI.

### ISSUE THREAD

**Issue by chiocla** [s0md3v/sd-webui-roop#46]
I had done below step. Why I cannot see roop drop-down menu. It show Error "No module named 'insightface'" when I restart UI. How to install the module?

Run this command: pip install insightface==0.7.3
In web-ui, go to the "Extensions" tab and use this URL https://github.com/s0md3v/sd-webui-roop in the "install from URL" tab.
Restart the UI

**Comment by alinasama** [comment]
I have the same issue, do you solve it?

**Comment by remghoost** [comment]
You have to activate your webui venv _before_ running that command.

Open a terminal/cmd in your `stable-diffusion-webui` folder
`"venv/scripts/activate"`
then run `pip install insightface==0.7.3`

**Comment by chiocla** [comment]
Thanks It works

**Comment by CeraRalaz** [comment]
> Open a terminal/cmd in your `stable-diffusion-webui` folder
> `"venv/scripts/activate"`
> then run `pip install insightface==0.7.3`

could you please elaborate for lamer user like me? 
We have in venv/scripts/ file activate.bat and activate
Activate.bat terminates itself, so you could not use it as cmd. Do we have to edit activate.bat with  pip install insightface==0.7.3 ?

**Comment by CeraRalaz** [comment]
> You have to activate your webui venv _before_ running that command.
> 
> Open a terminal/cmd in your `stable-diffusion-webui` folder `"venv/scripts/activate"` then run `pip install insightface==0.7.3`

note: This error originates from a subprocess, and is likely not a problem with pip.  ERROR: Failed building wheel for insightface
Failed to build insightfaceERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

Any hints why?

**Comment by BoyNG** [comment]
I try:

D:\stable-diffusion-portable-main>"venv/scripts/activate"
(venv) D:\stable-diffusion-portable-main>pip install insightface==0.7.3

got:

Fatal error in launcher: Unable to create process using '"C:\stable-diffusion-portable-main\venv\Scripts\python.exe"  "D:\stable-diffusion-portable-main\venv\Scripts\pip.exe" install insightface==0.7.3': ?? ??????? ????? ????????? ????.

**Comment by BoyNG** [comment]
update:
for solve - need this:
python -m pip install --upgrade pip

**Comment by anonfaker** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects


This is the error I"m getting can someone help>

**Comment by gavinggit** [comment]
When installing  - I got this message:
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I followed the link and did the (massive ) install of build tools/compiler.

Next time I ran it, it completed the build and the errors went away. YMMV.

**Comment by kholdstares** [comment]
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for insightface Failed to build insightface ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
> 
> This is the error I"m getting can someone help

Same problem, but trying to install ReActor.

**Comment by opticalix** [comment]
> I try:
> 
> D:\stable-diffusion-portable-main>"venv/scripts/activate" (venv) D:\stable-diffusion-portable-main>pip install insightface==0.7.3
> 
> got:
> 
> Fatal error in launcher: Unable to create process using '"C:\stable-diffusion-portable-main\venv\Scripts\python.exe" "D:\stable-diffusion-portable-main\venv\Scripts\pip.exe" install insightface==0.7.3': ?? ??????? ????? ????????? ????.

same issue, try check your python.exe or pip.exe path. No errors after edit the activate.bat and fix the path.

**Comment by Morzuchowsky** [comment]
Guys, 
For COMFY UI
Install it insightface thru model manager. It worked for me. 👍 
You can find it on the left in the menu.

just type insightface and then restart Comfy UI

![Image](https://github.com/user-attachments/assets/ef163967-d566-43b1-8856-1a7ab30774cd)
