### ISSUE TITLE
"When I try to start the Web UI after installing the plugin, I receive this error message. Even executing pip install protobuf==3.20 doesn't work."

### ISSUE THREAD

**Issue by netyingxiao** [s0md3v/sd-webui-roop#47]
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

------------------------------------------------------------------------------------------------------------------------

"When I try to start the Web UI after installing the plugin, I receive this error message. Even executing pip install protobuf==3.20 doesn't work."

**Comment by s0md3v** [comment]
installation problems are out of scope, use google.
