### ISSUE TITLE
  ModuleNotFoundError: No module named

### ISSUE THREAD

**Issue by jialeok** [s0md3v/sd-webui-roop#49]
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
  import insightface
ModuleNotFoundError: No module named 'insightface'
    from ifnude import detect
ModuleNotFoundError: No module named 'ifnude'
    File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'

**Comment by s0md3v** [comment]
installation problems are out of scope, use google.

**Comment by otorre1** [comment]
try 
pip install insightface
pip install ifnude
pip install Cython
