### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anvesh54321** [s0md3v/sd-webui-roop#50]
i used in google colab.
Error running postprocess_batch: /content/sdw/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/content/sdw/modules/scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: FaceSwapScript.postprocess_batch() got multiple values for argument 'images'

**Comment by ViliNeto** [comment]
I'm also getting this same error on local A1111

**Comment by watarukamei** [comment]
Error running postprocess_batch: F:\A1111WEebUI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py02it/s]
Traceback (most recent call last):
  File "F:\A1111WEebUI\stable-diffusion-webui\modules\scripts.py", line 487, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: FaceSwapScript.postprocess_batch() got multiple values for argument 'images'
