### ISSUE TITLE
Pixelated Face? O.o'

### ISSUE THREAD

**Issue by MaximilianPs** [s0md3v/sd-webui-roop#57]
I'm using a picture of 2048 x 1839 pixels and R-ESRGAN 4x+ as upscale, to render a picture at the same size, but I got a bunch of pixels on face and hairs wile the rest of the image is rendered as expected.

It's not a constant issue, sometimes Roop works very well. I think the problems tends to come out when we have some object that occlude part of the face.

![image](https://github.com/s0md3v/sd-webui-roop/assets/23430638/5da0da80-20f8-4d8e-8501-be823c333aa5)

**Comment by s0md3v** [comment]
The model roop uses wasn't created by me, nor it is possible for me to improve its output in any way.

A hack you can try is to use inpainting with a lot denoising strength.

**Comment by MaximilianPs** [comment]
Got it, however it seems that some LORAs can interfere with Roop and doing some misbehave (like "pixelize" the face) or stop it altogether.
Otherwise it works very well.
