### ISSUE TITLE
Is this only for realistic? Can you please make it effective for anime characters?

### ISSUE THREAD

**Issue by timmyhk852** [s0md3v/sd-webui-roop#59]
I tested with anythingv4 checkpoint to see if the extension can also model other anime characters' faces.
But it seems it cannot :(

Will you make it effective for anime characters?

**Comment by s0md3v** [comment]
I didn't create the model this extension uses, nor I can make changes to it :/

**Comment by markarenin** [comment]
> I tested with anythingv4 checkpoint to see if the extension can also model other anime characters' faces. But it seems it cannot :(
> 
> Will you make it effective for anime characters?

Hei, bro! Did you found face changer for anime?
