### ISSUE TITLE
bug in faceswap.py

### ISSUE THREAD

**Issue by GianlucaMattei** [s0md3v/sd-webui-roop#60]
in past days I used this extension without problems, today I am having this issue:

Error running process: /media/gm/ext/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
Traceback (most recent call last):
  File "/media/gm/ext/stable-diffusion-webui/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/media/gm/ext/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 153, in process
    int(x) for x in faces_index.strip(",").split(",") if x.isnumeric()
AttributeError: 'bool' object has no attribute 'strip'

I try to remove the folder and to reinstall the extension from automatic1111 extension tab but it didnt worked.

Any idea to fix this?

**Comment by GianlucaMattei** [comment]
It doesnt work only in txt2img but it works well in img2img

**Comment by s0md3v** [comment]
@GianlucaMattei Did you change anything in the code?

I have been using this extension for more than a week and I have never encountered this error. Moreover, I check and found out that its not possible for the variable face_index to be a boolean. I don't whats wrong on your end.

**Comment by ramnnv** [comment]
@s0md3v The same thing is happening to me. It was working well, but I updated roop with the extension tab, and stop working on Text to Img.

"Swap in source image" and "Swap in generated image" text and checkboxes are not showing on Text to Img, but showing on img to img.

I just reinstall Stable Difussion from 0 and roop extension again and still the same. I'm sure it was an update that caused this bug.

**Comment by s0md3v** [comment]
@ramnnv I read your comment, deleted the ext and reinstalled it. It works for me.

Maybe your webui version is old, idk.

**Comment by iuooip** [comment]
Although I have no error, I can see Roop in UI. I see that extension loads, but enabling it makes no effect.

I had to revert to [ccca35e43a40ba4ff078d4667d09cc3402db31af](https://github.com/s0md3v/sd-webui-roop/commit/ccca35e43a40ba4ff078d4667d09cc3402db31af), roop no longer works with text2img after changes in commits on Jun 22, 2023

```
automatic1111: commit baf6946e06249c5af9851c60171692c44ef633e0 (HEAD -> master, tag: v1.3.2, origin/master, origin/HEAD)
```

**Comment by Dizzmotron** [comment]
Looking through the code I noticed that swapper.py uses the variable fn, and the extension ControlNet also uses the same variable for some of its functions. As a test I changed fn to fnn, since I couldn't find that variable in use, and both ControlNet and Roop started working with txt2img. 

My Python level of understanding is about as low as it gets, but hopefully that points someone in the right direction.

**Comment by GianlucaMattei** [comment]
> @GianlucaMattei Did you change anything in the code?
> 
> I have been using this extension for more than a week and I have never encountered this error. Moreover, I check and found out that its not possible for the variable face_index to be a boolean. I don't whats wrong on your end.

Absolutely not :-(

**Comment by vjleoliu** [comment]
Error running postprocess_batch: E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\faceswap.py", line 183, in postprocess_image
    result: ImageResult = swap_face(
  File "E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\swapper.py", line 109, in swap_face
    converted = convert_to_sd(target_img)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\ifnude\detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Administrator\.ifnude/detector.onnx failed:Protobuf parsing failed.

**Comment by Bodzijun** [comment]
ERROR    Module load: D:\AI\seait_installers_version\automatic\extensions\sd-webui-roop\scripts\faceswap.py: SyntaxError
Module load: D:\AI\seait_installers_version\automatic\extensions\sd-webui-roop\scripts\faceswap.py: SyntaxError
╭───────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────╮
│ D:\AI\seait_installers_version\automatic\modules\script_loading.py:13 in load_module                                                                        │
│                                                                                                                                                             │
│   12 │   try:                                                                                                                                               │
│ ❱ 13 │   │   module_spec.loader.exec_module(module)                                                                                                         │
│   14 │   except Exception as e:                                                                                                                             │
│ in exec_module:879                                                                                                                                          │
│                                                                                                                                                             │
│                                                                   ... 1 frames hidden ...                                                                   │
│ in source_to_code:947                                                                                                                                       │
│ in _call_with_frames_removed:241                                                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  D:\AI\seait_installers_version\automatic\extensions\sd-webui-roop\scripts\faceswap.py:23                                                                   │
│ <<<<<<< Updated upstream                                                                                                                                    │
│ ▲                                                                                                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
SyntaxError: invalid syntax

**Comment by s0md3v** [comment]
Please use the latest version of webui.

**Comment by ameets21** [comment]
I tried with ImgtoImg but Face don't swap with uploaded reference face instead I get random faces.

**Comment by ameets21** [comment]
I even tried with inpaint but there no Faceswap
![Screenshot 2023-07-09 at 13-31-44 Stable Diffusion](https://github.com/s0md3v/sd-webui-roop/assets/7465991/c575d434-2307-475b-80ac-56ba80e9433f)
![Screenshot 2023-07-09 at 13-32-00 Stable Diffusion](https://github.com/s0md3v/sd-webui-roop/assets/7465991/d91548ac-6302-47f8-b2c8-4df0d23f1ed3)
![Screenshot 2023-07-09 at 13-32-16 Stable Diffusion](https://github.com/s0md3v/sd-webui-roop/assets/7465991/fbc8a775-d053-403e-8604-76f584be26a8)
![Screenshot 2023-07-09 at 13-32-29 Stable Diffusion](https://github.com/s0md3v/sd-webui-roop/assets/7465991/db3a1c1b-788c-4705-bcdf-2edca804a20e)

**Comment by ChongZomby** [comment]
I am also having no luck in txt2img, but I have found that for inpainting turning the Denoising Strength down to .01 gives the desired result. 

Hopefully this can help the previous poster (if nobody else).

**Comment by phaylali** [comment]
the problem is still in happening, please reopen the issue, it doesn't have any effect on the result, using up-to-date with git pull sd.next
