### ISSUE TITLE
API use

### ISSUE THREAD

**Issue by MichaelTzortzis** [s0md3v/sd-webui-roop#61]
Hello, I've been using this extension for a bit through the webui and everything works well (except with multiple faces which I cannot get to work). I now have the need though to use it through the sd webui API which is becoming quite the challenge. 

Is there any way to use this through the API? I have tried many payloads for the txt2img endpoint but even though ControlNet works fine it seems to ignore roop.

Any suggestions/insights?

**Comment by s0md3v** [comment]
Multiple faces work for me as intended and I have no plans to make it work with API nor I know about it enough too help you :/
