### ISSUE TITLE
You should at least have one model in models directory

### ISSUE THREAD

**Issue by Derelium** [s0md3v/sd-webui-roop#62]
![image](https://github.com/s0md3v/sd-webui-roop/assets/113668194/d0164e26-4ca0-4202-8f55-14fd10df66ff)
![image](https://github.com/s0md3v/sd-webui-roop/assets/113668194/950f9b88-5dc2-4b7e-b863-9b9418707676)
![image](https://github.com/s0md3v/sd-webui-roop/assets/113668194/d33bc055-992d-471b-be6d-c77872293af5)

**Comment by s0md3v** [comment]
wrong directory. check readme.
