### ISSUE TITLE
[Feature Request] Multiple Faces

### ISSUE THREAD

**Issue by DennLie** [s0md3v/sd-webui-roop#63]
It would be great to be able to use multiple faces. For example i take the faces of me and my wife and assign face 1 of the generated image to mine and the second to my wife.

**Comment by s0md3v** [comment]
This will not be worked on.

**Comment by Gh20221205** [comment]
> It would be great to be able to use multiple faces. For example i take the faces of me and my wife and assign face 1 of the generated image to mine and the second to my wife.

try face editor, you will be surprised

**Comment by grebnebo** [comment]
why? with this feature we will gain ability to produce our own movies. Just wonder "terminator 2" with your friends! That could be great.
for example first
1) generate face db with ID's
2) swap all unique faces with your photo
3) PROFIT!!!
