### ISSUE TITLE
GPU suport request !!  warning message : Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

### ISSUE THREAD

**Issue by AI-Robot-Morris** [s0md3v/sd-webui-roop#68]
After updated roop today,

the roop still use CPU not GPU? 

Warning message shows 
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

Looking for solution or hints for GPU support

**Comment by s0md3v** [comment]
I posted a comment in another issue, find it

**Comment by KakaoXI** [comment]
> I posted a comment in another issue, find it

Where

**Comment by PANLI77** [comment]
How to deal with it?

> 我在另一期中发表了评论，找到了

**Comment by spector32** [comment]
> I posted a comment in another issue, find it

Very bad answer! At least link this issue to it...
