### ISSUE TITLE
Do I need to install C++14 and python to use it on a Linux system?

### ISSUE THREAD

**Issue by liuhaowei-littlebird** [s0md3v/sd-webui-roop#70]

**Comment by s0md3v** [comment]
read the docs

**Comment by tensiondriven** [comment]
I think it would be useful to a lot of people, and save significant time/questions/effort, if the readme had a section for Linux listing the (lack of) requirements and install method.  This (as you no doubt know) is pretty typical for most projects.

**Comment by TheSeventhCode** [comment]
Agreed, just a small mention that the entire Visual Studio section isn't required on Linux would clear up quite a few questions.
