### ISSUE TITLE
cannot install it on vladUI? ERROR    Error running extension installer: D:\vlad\automatic\extensions\sd-webui-roop\install.py

### ISSUE THREAD

**Issue by StableInfo** [s0md3v/sd-webui-roop#79]
Hello,
I tried to install it from the extensions tab on vlad webui (similar to auto webui), when i restarted the bat file I keep getting this:
`ERROR    Error running extension installer: D:\vlad\automatic\extensions\sd-webui-roop\install.py`

Edge, first version of vlad UI.

**Comment by StableInfo** [comment]
Edit:: additional stuff:
Module load: D:\vlad\automatic\extensions\sd-webui-roop\scripts\cimage.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\vlad\automatic\modules\script_loading.py:10 in load_module                                                       │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\vlad\automatic\extensions\sd-webui-roop\scripts\cimage.py:2 in <module>                                          │
│                                                                                                                     │
│    1 import tempfile                                                                                                │
│ >  2 from ifnude import detect                                                                                      │
│    3                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'ifnude'
Module load: D:\vlad\automatic\extensions\sd-webui-roop\scripts\faceswap.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\vlad\automatic\modules\script_loading.py:10 in load_module                                                       │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ D:\vlad\automatic\extensions\sd-webui-roop\scripts\faceswap.py:15 in <module>                                       │
│                                                                                                                     │
│    14 from scripts.roop_logging import logger                                                                       │
│ >  15 from scripts.swapper import UpscaleOptions, swap_face, ImageResult                                            │
│    16 from scripts.roop_version import version_flag                                                                 │
│                                                                                                                     │
│ D:\vlad\automatic\extensions\sd-webui-roop\scripts\swapper.py:12 in <module>                                        │
│                                                                                                                     │
│    11                                                                                                               │
│ >  12 import insightface                                                                                            │
│    13 import onnxruntime                                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'insightface'
Module load: D:\vlad\automatic\extensions\sd-webui-roop\scripts\swapper.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\vlad\automatic\modules\script_loading.py:10 in load_module                                                       │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\vlad\automatic\extensions\sd-webui-roop\scripts\swapper.py:12 in <module>                                        │
│                                                                                                                     │
│    11                                                                                                               │
│ >  12 import insightface                                                                                            │
│    13 import onnxruntime                                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'insightface'

**Comment by s0md3v** [comment]
only automatic webui is officially supported

**Comment by StableInfo** [comment]
can you suppot vlad ui? its almost the same.

**Comment by StableInfo** [comment]
@s0md3v  Some additional info:
https://www.reddit.com/r/StableDiffusion/comments/12srusf/vladmandic_vs_automatic1111_vlads_ui_is_almost_2x/
https://www.reddit.com/r/StableDiffusion/comments/13wggk4/some_nice_recent_sdnext_aka_vlad_diffusion_updates/
You really should support it. Recondiser, thanks.

**Comment by giandre** [comment]
I second this as well. I use vlad and I am unable to use this option.

**Comment by cleverestx** [comment]
Please support VLAD too..many people use it as well. Thanks.

**Comment by StableInfo** [comment]
Can you guys make new posts about this to inform him? Maybe he is not getting notifications

**Comment by cleverestx** [comment]
> Can you guys make new posts about this to inform him? Maybe he is not getting notifications

He should be getting this tag when he's tagged, right? Like this:  @s0md3v 

Please do look into this more s0md3v! I'd love to use this extension in Vladmandic

**Comment by StableInfo** [comment]
I found a page saying its supporting vlad ui: 
https://github.com/glucauze/sd-webui-faceswaplab

**Comment by cleverestx** [comment]
I got rhe "unofficial" Roop working (uncensored one) in Sd.Next. it is supported fine.

**Comment by StableInfo** [comment]
Which is?
