### ISSUE TITLE
安装时就出问题了！

### ISSUE THREAD

**Issue by santtyjay** [s0md3v/sd-webui-roop#86]
webui内扩展从网址安装，输入网址后点安装，提示：GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- https://github.com/s0md3v/sd-webui-roop E:\novelai-webui\novelai-webui\novelai-webui-aki-v3\tmp\sd-webui-roop stderr: 'Cloning into 'E:\novelai-webui\novelai-webui\novelai-webui-aki-v3\tmp\sd-webui-roop'... fatal: unable to access 'https://github.com/s0md3v/sd-webui-roop/': SSL certificate problem: unable to get local issuer certificate '

**Comment by s0md3v** [comment]
This is a problem on your end. It is not related to this extension.
