### ISSUE TITLE
Downloading the detection model to /root/.ifnude/detector.onnx failed

### ISSUE THREAD

**Issue by QiuLL** [s0md3v/sd-webui-roop#87]
Downloading the detection model to /root/.ifnude/detector.onnx failed, so can't start the script rightly,hope someone can give me some advice

**Comment by s0md3v** [comment]
I assume you are from china and are facing restrictions, I can't help with that.

**Comment by k186** [comment]
你如果用的集合包， 在设置里面代理设置 的代理服务器地址改为你的本地代理端口就可以了

**Comment by Tongzhou-Yu** [comment]
这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

**Comment by QiuLL** [comment]
谢谢，respect!



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月30日 23:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [s0md3v/sd-webui-roop] Downloading the detection model to /root/.ifnude/detector.onnx failed (Issue #87) |

这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx
