### ISSUE TITLE
Error: Error running postprocess_batch,  & AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by windwe2** [s0md3v/sd-webui-roop#95]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Admin/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Error running postprocess_batch: E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "E:\sd-webui-aki-v4\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
    result = face_swapper.get(result, target_face, source_face)
AttributeError: 'NoneType' object has no attribute 'get'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by oldtreee** [comment]
Have you solved it

**Comment by oldtreee** [comment]
I encountered the same problem, but there was no such error when I used 0.0.1

**Comment by oldtreee** [comment]
If you encounter 'NoneType' object has no attribute 'get' error, download the inswapper_128.onnx model and put it inside <webui_dir>/models/roop/ directory.

**Comment by coder-rishav** [comment]
Same here, any solution ?

**Comment by osama88** [comment]
Have you solved it ??

**Comment by gunnarsal** [comment]
> If you encounter 'NoneType' object has no attribute 'get' error, download the inswapper_128.onnx model and put it inside <webui_dir>/models/roop/ directory.

I have the file in the folder \automatic\extensions\sd-webui-roop\models\roop just in case even redownloaded it but still the same error.

Could there be an issue because I use Vlad instead of regular A1111? 

I see that there is a section under Roop asking to download model. What model does it mean?
<img width="636" alt="image" src="https://github.com/s0md3v/sd-webui-roop/assets/129676685/f86ac223-7cdf-49dc-b108-3d775dce48e2">

**Comment by s0md3v** [comment]
Read docs.
