### ISSUE TITLE
Error about the ifnude/detector.onnx

### ISSUE THREAD

**Issue by ylmalta** [s0md3v/sd-webui-roop#98]
Error about the ifnude/detector.onnx

seem like the faceswap not work for me ,beacuse   ifnude/detector.onnx this file corrupted when I download, and I was not able to find the download url for detector.onnx, could anyone share with me? so many thanks

**Comment by coolzilj** [comment]
model_url = "https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx"
classes_url = "https://huggingface.co/s0md3v/nudity-checker/resolve/main/classes"

**Comment by ylmalta** [comment]
> model_url = "https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx" classes_url = "https://huggingface.co/s0md3v/nudity-checker/resolve/main/classes"

thanks so much man, you saving me several hours

**Comment by k186** [comment]
你如果用的集合包， 在设置里面代理设置 的代理服务器地址改为你的本地代理端口就可以了

**Comment by ylmalta** [comment]
谢谢

YPanda ***@***.***> 于2023年6月29日周四 22:42写道：

**Comment by Tongzhou-Yu** [comment]
这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx
