### ISSUE TITLE
Does sd-webui-roop work with AMD RX Vega 56 GPU with Rocm in Ubuntu Liunx?

### ISSUE THREAD

**Issue by BahzBeih** [s0md3v/sd-webui-roop#99]
Peace, does sd-webui-roop work with AMD RX Vega 56 GPU with Rocm in Ubuntu Linux? , and with AMD GPUS in General?

**Comment by Gourieff** [comment]
It uses CPU Execution Provider at the moment, not GPU, so no matter what platform you have - it might work

**Comment by s0md3v** [comment]
GPU is slower than CPU for a single frame i.e. photo. We use CPU.
